repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        files: '\.(md|py|rst)$'

  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        language_version: default
        files: '\.py$'
        args: ['--exclude', 'src/file_parser/devices/']

  - repo: https://github.com/pycqa/isort
    rev: 7.0.0
    hooks:
      - id: isort
        files: '\.py$'
        args: ['--skip', 'src/file_parser/devices/']

  - repo: https://github.com/pycqa/pylint
    rev: v4.0.2
    hooks:
      - id: pylint
        args: ['--rcfile=.pylintrc']

  - repo: local
    hooks:
      - id: check-uk-english
        name: check-uk-english
        entry: python .github/scripts/check_uk_english.py
        language: python
        language_version: default
        files: '\.(md|py|rst)$'
        exclude: '^\.github/(scripts|tools)/'  # Ignore the helper scripts and archived tools
        pass_filenames: true