# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: CGM Data Processor
site_url: https://Warren8824.github.io/cgm-data-processor
repo_url: https://github.com/Warren8824/cgm-data-processor
repo_name: Warren8824/cgm-data-processor

theme:
  name: material
  palette:
    scheme: slate
    primary: teal
  features:
    - header.autohide
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
            show_root_heading: true
            show_root_full_path: true
            show_if_no_docstring: true
            show_signature_annotations: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      auto_title: false
  - admonition
  - pymdownx.superfences
  - pymdownx.details  # This is needed for the ??? expandable sections
  - tables
  - footnotes
  - def_list

nav:
  - Home: index.md
  - Tutorials:
      - Loading and Exporting Data: tutorials/load_and_export_data.md
  - API Reference:
      - Reference: api/reference.md
      - Loading: api/loading.md
      - Cleaning: api/cleaning.md
      - Alignment: api/alignment.md