# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: CGM Data Processor
site_url: https://Warren8824.github.io/cgm-data-processor
repo_url: https://github.com/Warren8824/cgm-data-processor
repo_name: Warren8824/cgm-data-processor

theme:
  name: material
  palette:
    scheme: slate
    primary: teal
  features:
    - header.autohide
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
            show_root_heading: true
            show_root_full_path: true
            show_if_no_docstring: true
            show_signature_annotations: true

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      auto_title: false
  - admonition
  - pymdownx.superfences
  - pymdownx.details  # This is needed for the ??? expandable sections
  - tables
  - footnotes
  - def_list

nav:
  - Home: index.md
  - Getting Started:
    - Installation: installation/index.md
  - User Guide:
    - Tutorials:
      - Loading and Exporting Data: user-guide/tutorials/load_and_export_data.md
    - Concepts:
      - Data Processing Pipeline: user-guide/concepts/processing_pipeline.md
      - Gap Analysis: user-guide/concepts/gap_analysis.md
  - API Reference:
    - Overview: api/index.md
    - Preprocessing:
      - Data Loading: api/preprocessing/loading.md
      - Data Cleaning: api/preprocessing/cleaning.md
      - Data Alignment: api/preprocessing/alignment.md
    - Analysis:
      - CGM Gap Analysis: api/analysis/gaps.md
    - Visualization:
      - Gap Analysis Dashboard: api/visualisation/gap_dashboard.md
    - Complete Reference: api/reference.md
  - Development:
    - Contributing: development/contributing.md
    - Roadmap: development/roadmap.md
  - About:
    - Changelog: about/changelog.md
    - License: about/license.md