# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: CGM Data Processor
site_url: https://Warren8824.github.io/cgm-data-processor
repo_url: https://github.com/Warren8824/cgm-data-processor
repo_name: Warren8824/cgm-data-processor

theme:
  name: material
  palette:
    scheme: slate
    primary: black
  features:
    - header.autohide
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
            show_root_heading: true
            show_root_full_path: true
            show_if_no_docstring: true
            show_signature_annotations: true

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      auto_title: false
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.details  # This is needed for the ??? expandable sections
  - tables
  - footnotes
  - def_list

nav:
  - Home: index.md

  - Getting Started:
    - Overview: getting-started/index.md
    - Installation: getting-started/installation.md
    - Quick Start: getting-started/quickstart.md
    - Command Line Usage: getting-started/cli-usage.md

  - User Guide:
    - Overview: user-guide/index.md
    - Understanding Data Types:
      - Overview: user-guide/data-types/index.md
      - CGM Data: user-guide/data-types/cgm.md
      - Insulin Data: user-guide/data-types/insulin.md
      - Carbohydrate Data: user-guide/data-types/carbs.md
      - Notes & Events: user-guide/data-types/notes.md
    - Supported Devices:
      - Overview: user-guide/devices/index.md
      - Dexcom: user-guide/devices/dexcom.md
      - Libre: user-guide/devices/libre.md
      - XDrip+: user-guide/devices/xdrip.md
    - Data Processing:
      - Overview: user-guide/processing/index.md
      - Data Alignment: user-guide/processing/alignment.md
      - Data Validation: user-guide/processing/validation.md
      - Error Handling: user-guide/processing/errors.md

  - API Reference:
    - Overview: api/index.md
    - Core Components:
      - Data Types: api/core/data-types.md
      - Format Registry: api/core/format-registry.md
      - Data Alignment: api/core/alignment.md
      - Exceptions: api/core/exceptions.md
    - File Parsing:
      - Overview: api/file-parsing/index.md
      - Format Detection: api/file-parsing/format-detection.md
      - Readers: api/file-parsing/readers.md
    - Data Processing:
      - Overview: api/processing/index.md
      - Base Processor: api/processing/base-processor.md
      - CGM Processing: api/processing/cgm.md
      - Insulin Processing: api/processing/insulin.md
      - Carbs Processing: api/processing/carbs.md
      - Notes Processing: api/processing/notes.md

  - Developer Guide:
    - Overview: dev-guide/index.md
    - Contributing: dev-guide/contributing.md
    - Project Structure: dev-guide/project-structure.md
    - Adding New Formats:
      - Overview: dev-guide/formats/index.md
      - Format Definition: dev-guide/formats/definition.md
      - Format Validation: dev-guide/formats/validation.md
      - Testing Formats: dev-guide/formats/testing.md
    - Adding New Processors:
      - Overview: dev-guide/processors/index.md
      - Processor Development: dev-guide/processors/development.md
      - Testing Processors: dev-guide/processors/testing.md

  - About:
    - Project Goals: about/index.md
    - Changelog: about/changelog.md
    - License: about/license.md