# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Data Processor Documentation
site_url: https://Warren8824.github.io/cgm-data-processor
repo_url: https://github.com/Warren8824/cgm-data-processor
repo_name: Warren8824/cgm-data-processor
site_description: "Python package for processing diabetes device data"
site_author: "Warren8824"
copyright: |
  <div style="text-align: center; padding: 10px 0;">
    <a href="https://github.com/Warren8824/cgm-data-processor/commits/main">
      <img src="https://img.shields.io/github/last-commit/Warren8824/cgm-data-processor" alt="Last Commit">
      <img src="https://img.shields.io/github/commit-activity/m/Warren8824/cgm-data-processor" alt="Monthly Commits">
    </a>
    <img src="https://img.shields.io/github/languages/top/Warren8824/cgm-data-processor" alt="Language">
    <img src="https://img.shields.io/github/repo-size/Warren8824/cgm-data-processor" alt="Repo Size">
    <img src="https://img.shields.io/github/license/Warren8824/cgm-data-processor" alt="License">
    <img src="https://img.shields.io/github/issues/Warren8824/cgm-data-processor" alt="Issues">
    <img src="https://img.shields.io/github/stars/Warren8824/cgm-data-processor?style=social" alt="Stars">
    <img src="https://img.shields.io/github/forks/Warren8824/cgm-data-processor?style=social" alt="Forks">
  </div>

theme:
  logo: assets/logo_white.png
  favicon: assets/logo_padded.png
  name: material
  palette:
    # Add media toggle for light/dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - announce.dismiss
    - header.autohide
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top        # Add back-to-top button
    - search.highlight     # Highlight search results
    - search.share        # Add search sharing
    - content.code.copy
    - content.code.annotate

extra_css:
  - stylesheets/extra.css
extra:
  generator: false  # Disable "Generated by MkDocs" in footer
plugins:
  - git-revision-date-localized:
      enable_creation_date: true  # Also show when files were created
  - minify:
      minify_html: true
  - redirects:
      redirect_maps: {}
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])' # Better search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_full_path: true
            show_if_no_docstring: true
            show_signature_annotations: true
            members_order: source
            heading_level: 2

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      auto_title: false
      linenums: true           # Add line numbers to code blocks
      linenums_style: table    # Table style for line numbers
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - tables
  - footnotes
  - def_list
  - toc:                       # Add table of contents support
      permalink: true
      toc_depth: 3

nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started/index.md
    - Installation: getting-started/installation.md
    - Quick Start Guide:
      - Basic Usage: getting-started/quickstart/basic.md
      - Data Import: getting-started/quickstart/import.md
      - Data Processing: getting-started/quickstart/processing.md
  - User Guide:
    - Data Types & Processing: user-guide/data-types.md
    - Supported Formats: user-guide/formats.md
    - Error Handling: user-guide/errors.md
  - API Reference:
    - Core API:
        - Data Types API: api/core/data-types.md
        - Format Registry API: api/core/format-registry.md
        - Aligner API: api/core/aligner.md
        - Exceptions API: api/core/exceptions.md
    - Format Detection API: api/file_parser.md
    - Readers API: api/readers.md
    - Processors API: api/processors.md
    - Exporters API: api/exporters.md
  - Contributing:
    - Development Guide: contributing/guide.md
    - License: contributing/license.md
    - Adding New Formats: contributing/formats.md
    - Adding New Processors: contributing/processors.md