# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Data Processor Documentation
site_url: https://Warren8824.github.io/cgm-data-processor
repo_url: https://github.com/Warren8824/cgm-data-processor
repo_name: Warren8824/cgm-data-processor
site_description: "Python package for processing diabetes device data"
site_author: "Warren8824"

theme:
  logo: assets/logo_white.png
  favicon: assets/logo_padded.png
  name: material
  palette:
    scheme: slate
    primary: teal
    accent: teal
  features:
    - announce.dismiss
    - header.autohide
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - content.code.annotate

plugins:
  - git-revision-date-localized
  - minify:
      minify_html: true
  - redirects:
      redirect_maps: { }
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
            show_root_heading: true
            show_root_full_path: true
            show_if_no_docstring: true
            show_signature_annotations: true

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      auto_title: false
  - admonition
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.details  # This is needed for the ??? expandable sections
  - tables
  - footnotes
  - def_list

nav:
  - Home: index.md
  - Getting Started:
    - Overview: getting-started/index.md
    - Installation: getting-started/installation.md
    - Quick Start Guide:
      - Basic Usage: getting-started/quickstart/basic.md
      - Data Import: getting-started/quickstart/import.md
      - Data Processing: getting-started/quickstart/processing.md

  - User Guide:
    - Data Types & Processing: user-guide/data-types.md
    - Supported Formats: user-guide/formats.md
    - Error Handling: user-guide/errors.md

  - API Reference:
    - Core API: api/core.md
    - Readers API: api/readers.md
    - Processors API: api/processors.md

  - Contributing:
    - Development Guide: contributing/guide.md
    - Adding New Formats: contributing/formats.md
    - Adding New Processors: contributing/processors.md