# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: CGM Data Processor
site_url: https://Warren8824.github.io/cgm-data-processor
repo_url: https://github.com/Warren8824/cgm-data-processor
repo_name: Warren8824/cgm-data-processor

theme:
  name: material
  palette:
    scheme: slate
    primary: teal
  features:
    - header.autohide
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
            show_root_heading: true
            show_root_full_path: true
            show_if_no_docstring: true
            show_signature_annotations: true

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      auto_title: false
  - admonition
  - pymdownx.superfences
  - pymdownx.details  # This is needed for the ??? expandable sections
  - tables
  - footnotes
  - def_list

nav:
  - Home: index.md
  - Installation: installation/index.md
  - Tutorials:
      - Loading and Exporting Data: tutorials/load_and_export_data.md
  - API Reference:
      - Data Loading: api/preprocessing/loading.md
      - Data Cleaning: api/preprocessing/cleaning.md
      - Data Alignment: api/preprocessing/alignment.md
      - CGM Gap Analysis: api/analysis/gaps.md
      - CGM Gap Analysis Dashboard: api/visualisation/gap_dashboard.md
      - Complete API Reference: api/reference.md