site_name: CGM Data Processor
site_url: https://Warren8824.github.io/cgm-data-processor
repo_url: https://github.com/Warren8824/cgm-data-processor
repo_name: Warren8824/cgm-data-processor

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
            show_root_heading: true
            show_root_full_path: true
            show_if_no_docstring: true
            show_signature_annotations: true
          setup_commands:
            - import sys
            - from pathlib import Path
            - sys.path.append(str(Path().resolve()))

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      auto_title: false
  - admonition
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.inlinehilite
  - tables
  - footnotes
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

nav:
  - Home: index.md
  - Tutorials:
      - Loading and Exporting Data: tutorials/load_and_export_data.md
  - API Reference:
      - Loading: api/loading.md
      - Cleaning: api/cleaning.md