# Book settings
title: Gastro_eda_book
author: Warren Bebbington
logo: logo.png

execute:
  execute_notebooks: force

latex:
  latex_documents:
    targetname: book.tex

repository:
  url: https://github.com/executablebooks/jupyter-book
  path_to_book: docs
  branch: master

html:
  use_issues_button: true
  use_repository_button: true

sphinx:
  extra_extensions:
    - sphinx.ext.autodoc
    - sphinx.ext.napoleon
    - sphinx.ext.viewcode
    - sphinx.ext.intersphinx
    - hoverxref.extension
  config:
    # Python documentation settings
    autodoc_member_order: bysource
    autodoc_typehints: description
    python_use_unqualified_type_names: true

    # Add your source code directory
    sys_path: ['..']  # This tells Sphinx to look one directory up from the docs

    # Intersphinx mappings
    intersphinx_mapping:
      python: ['https://docs.python.org/3', null]

    # HoverXRef settings
    hoverxref_role_types:
      ref: tooltip
      func: tooltip
      meth: tooltip
      class: tooltip
      mod: tooltip
    hoverxref_default_type: tooltip
    hoverxref_auto_ref: true
    hoverxref_roles: ['func', 'meth', 'class', 'mod', 'ref']
    hoverxref_domains: ['py']

    # Tooltip appearance
    hoverxref_tooltip_lazy: false
    hoverxref_tooltip_maxwidth: 450
    hoverxref_tooltip_side: right
    hoverxref_tooltip_animation: fade
    hoverxref_tooltip_theme: ['tooltipster-shadow', 'tooltipster-shadow-custom']

    hoverxref_sphinxtabs: true