name: Tests & Coverage

on:
  push:
    branches: [ add-tests, main ]
  pull_request:
    branches: [ add-tests, main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up Python
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    # Step 3: Install dependencies (including dev tools)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --with dev

    # Step 4: Install pre-commit (Poetry already installed it, but bin needs exposing)
    - name: Install pre-commit (ensure CLI available)
      run: pip install pre-commit

    # Step 5: Run all pre-commit hooks
    - name: Run pre-commit
      run: pre-commit run --all-files

    # Step 6: Run tests with coverage
    - name: Run tests with coverage
      run: |
        poetry run pytest --cov=src --cov-report=xml --cov-report=term-missing tests/

    # Step 7: Generate coverage badge (saved locally to docs/assets)
    - name: Generate coverage badge
      run: |
        poetry run coverage-badge -o docs/assets/coverage.svg -f

    # Step 8: Upload badge as artifact so we can inspect it in CI
    - name: Upload coverage badge artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-badge
        path: docs/assets/coverage.svg
